# Generated by Django 2.2.5 on 2019-09-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='e_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='n_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='s_to',
        ),
        migrations.RemoveField(
            model_name='room',
            name='w_to',
        ),
        migrations.AddField(
            model_name='room',
            name='east',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='north',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='south',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='touched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='west',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
