# Generated by Django 2.2.5 on 2019-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190925_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Crumbling Halls of Ascendance', max_length=50),
        ),
    ]
