# Generated by Django 2.2.5 on 2019-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20190925_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=50),
        ),
    ]
