# Generated by Django 2.2.5 on 2019-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_auto_20190925_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Lost Crypt of Destruction', max_length=50),
        ),
    ]
