# Generated by Django 2.2.5 on 2019-09-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20190925_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='Rusty Laboratory of Mortality', max_length=50),
        ),
    ]
