# Generated by Django 2.2.5 on 2019-09-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0005_auto_20190925_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default='DEFAULT DESCRIPTION', max_length=50),
        ),
    ]
